# Generated by Django 5.0.1 on 2024-02-10 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 21, 9, 12, 217491)),
        ),
    ]
